#!/bin/sh

set -e

# Get rid of the old 'stterm' alternative.
# Since version 0.8.1-1 the binary is called 'st'.
update-alternatives --remove x-terminal-emulator /usr/bin/stterm

# Install the new alternative.
update-alternatives \
  --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/st 15 \
  --slave /usr/share/man/man1/x-terminal-emulator.1.gz x-terminal-emulator.1.gz /usr/share/man/man1/st.1.gz

#DEBHELPER#

exit 0
