#!/bin/sh

set -e

# Get rid of the old 'stterm' alternative.
# Since version 0.8.1-1 the binary is called 'st'.
update-alternatives --remove x-terminal-emulator /usr/bin/stterm

# Install the new alternative.
update-alternatives \
  --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/st 15

# Set st to be the default terminal.
update-alternatives --set x-terminal-emulator /usr/bin/st

#DEBHELPER#

exit 0
